schema_version = "1.0.0"

id = "subdiv_methods"
version = "1.0.0"
name = "Subdivision Methods"
tagline = "Apply subdivision surface modifier easily"
maintainer = "Sudhanva Joshi>"
type = "add-on"
tags = ["Modeling", "Mesh"]
blender_version_min = "4.0.0"
license = ["SPDX:GPL-3.0-or-later"]
