schema_version = "1.0.0"

id = "subdiv_methods"
version = "1.0.0"
name = "Subdivision Methods"
tagline = "Apply subdivision algorithms"
description = "Provides quick access to different subdivision algorithms with customizable levels"
maintainer = "Sudhanva Joshi"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.0.0"
license = ["SPDX:GPL-3.0-or-later"]
